// Generated by scripts/export_contracts.py. Do not edit by hand.
// Runtime validation and size limits are defined by contracts/openapi.json.

export type Catalog = {
  "doc_types": Array<DocumentType>;
  "templates": Array<Template>;
  "processor_mode": string;
};

export type DocumentContentInput = {
  "doc_type": string;
  "requisites"?: Record<string, string>;
  "body": Array<string>;
};

export type DocumentContent = {
  "doc_type": string;
  "requisites": Record<string, string>;
  "body": Array<string>;
};

export type DocumentType = {
  "id": string;
  "name": string;
  "description": string;
  "title": string;
  "fields": Array<RequisiteField>;
  "blocks": Array<string>;
};

export type DownloadRequest = {
  "document": DocumentContentInput;
  "template_id": string;
};

export type ErrorInfo = {
  "code": string;
  "message": string;
  "retryable": boolean;
  "request_id": string;
  "details": Array<ErrorIssue>;
};

export type ErrorIssue = {
  "field": string;
  "message": string;
  "type": string;
};

export type ErrorResponse = {
  "detail": string;
  "error": ErrorInfo;
};

export type HealthResponse = {
  "status": "ok";
  "processor_mode": string;
};

export type ProcessRequest = {
  "doc_type": string;
  "draft": string;
  "requisites"?: Record<string, string>;
};

export type ProcessResponse = {
  "document": DocumentContent;
  "missing_fields": Array<RequisiteField>;
  "changes": Array<string>;
  "warnings": Array<string>;
  "processor_mode": string;
};

export type ReadyResponse = {
  "status": "ready";
  "processor_mode": string;
  "checks": Record<string, boolean>;
};

export type RequisiteField = {
  "id": string;
  "label": string;
  "required": boolean;
};

export type Template = {
  "id": string;
  "name": string;
  "description": string;
  "font": string;
  "font_size": number;
  "margins_mm": Record<string, number>;
  "line_spacing": number;
  "paragraph_space_after_pt": number;
  "first_line_indent_mm": number;
  "title_alignment": "left" | "center" | "right" | "justify";
  "recipient_alignment": "left" | "center" | "right" | "justify";
  "body_alignment": "left" | "center" | "right" | "justify";
};

export type ProcessResult = ProcessResponse;
