"""Export reproducible API contracts; --check fails if committed files drift."""

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))

from app.content_policy import ModelOutput
from app.main import create_app
from app.settings import Settings


def type_name(name: str) -> str:
    name = name.replace("-Output", "").replace("-Input", "Input")
    return re.sub(r"[^a-zA-Z0-9_]", "_", name)


def typescript(schema: dict) -> str:
    if "$ref" in schema:
        return type_name(schema["$ref"].split("/")[-1])
    if "const" in schema:
        return json.dumps(schema["const"], ensure_ascii=False)
    if "enum" in schema:
        return " | ".join(
            json.dumps(value, ensure_ascii=False) for value in schema["enum"]
        )
    if "anyOf" in schema:
        return " | ".join(typescript(value) for value in schema["anyOf"])
    kind = schema.get("type")
    if kind in {"string", "boolean", "null"}:
        return kind
    if kind in {"integer", "number"}:
        return "number"
    if kind == "array":
        return f"Array<{typescript(schema['items'])}>"
    if kind == "object":
        props = schema.get("properties", {})
        if props:
            required = schema.get("required", [])
            fields = [
                f"  {json.dumps(key)}{'' if key in required else '?'}: {typescript(value)};"
                for key, value in props.items()
            ]
            return "{\n" + "\n".join(fields) + "\n}"
        patterns = schema.get("patternProperties", {})
        if patterns:
            values = " | ".join(typescript(value) for value in patterns.values())
            return f"Record<string, {values}>"
        values = schema.get("additionalProperties", True)
        if isinstance(values, dict):
            return f"Record<string, {typescript(values)}>"
        return "Record<string, unknown>" if values else "Record<string, never>"
    raise ValueError(f"Unsupported JSON Schema construct: {schema}")


def render_contracts() -> dict[str, str]:
    application = create_app(Settings(_env_file=None, text_processor="stub"))
    spec = application.openapi()
    schema = ModelOutput.model_json_schema()
    definitions = spec["components"]["schemas"]
    output = [
        "// Generated by scripts/export_contracts.py. Do not edit by hand.",
        "// Runtime validation and size limits are defined by contracts/openapi.json.",
        "",
    ]
    for name, definition in sorted(definitions.items()):
        output += [f"export type {type_name(name)} = {typescript(definition)};", ""]
    output += ["export type ProcessResult = ProcessResponse;", ""]
    return {
        "openapi.json": json.dumps(spec, ensure_ascii=False, indent=2, sort_keys=True)
        + "\n",
        "llm-output.schema.json": json.dumps(
            schema, ensure_ascii=False, indent=2, sort_keys=True
        )
        + "\n",
        "api.ts": "\n".join(output),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    options = parser.parse_args()
    output_dir = ROOT / "contracts"
    stale = []
    contracts = render_contracts()
    files = {output_dir / name: content for name, content in contracts.items()}
    # Keep the same contract inside the frontend Docker context, also checked in CI.
    files[ROOT / "frontend/src/generated/api.ts"] = contracts["api.ts"]
    for path, content in files.items():
        if options.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
    if stale:
        print(
            "Outdated contracts: "
            + ", ".join(stale)
            + ". Run scripts/export_contracts.py."
        )
        return 1
    print(
        "Contracts are current."
        if options.check
        else "Exported OpenAPI, LLM schema and TypeScript."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
